import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from '@src/app/app.component';
import { CardComponent } from '@src/app/card/card.component';
import { NavComponent } from '@src/app/nav/nav.component';
import { MoreCardComponent } from '@src/app/more-card/more-card.component';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { ModalComponent } from '@src/app/modal/modal.component';

@NgModule({
  declarations: [
    AppComponent,
    CardComponent,
    NavComponent,
    MoreCardComponent,
    AutoGeneratedComponent,
    ModalComponent
  ],
  imports: [
    BrowserModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
